In [11]:
import pandas as pd
import os

In [12]:
CURRENT_PATH = os.getcwd()
PATH_TO_FILES = "/home/pfl/Ironhack/project_Searching_for_Arbitrage_Opportunities_in_the_FX_Market_on_the_paper/datasets_csv"
filescsv = os.listdir(PATH_TO_FILES)
os.chdir(PATH_TO_FILES)
os.getcwd()

'/home/pfl/Ironhack/project_Searching_for_Arbitrage_Opportunities_in_the_FX_Market_on_the_paper/datasets_csv'

In [13]:
df_names_columns_all_files = pd.DataFrame()

In [14]:
for file in range(3):
    df = pd.read_csv(filescsv[file])
    df_names_columns_all_files[f"{filescsv[file]}"] = df.columns

In [26]:
df_names_columns_all_files.isin(df.columns)

,Xasmus.17302.PERIOD_M1.EURNZDmicro.csv,Xasmus.23925.PERIOD_M1.USDMXNmicro.csv,Xasmus.25659.PERIOD_M1.AUDCADmicro.csv
0,True,True,True
1,True,True,True
2,True,True,True
3,True,True,True
4,True,True,True
5,True,True,True
6,True,True,True
7,True,True,True
8,True,True,True
9,True,True,True
10,True,True,True
11,True,True,True
12,True,True,True
13,True,True,True
14,True,True,True
15,True,True,True
16,True,True,True
17,True,True,True
18,True,True,True

In [25]:
for col in df.columns:
    print(df[f"{col}"])
    print("canvi de columna")

0          2015.01.02 08:06:00
1          2015.01.02 08:07:01
2          2015.01.02 08:08:00
3          2015.01.02 08:09:00
4          2015.01.02 08:10:00
                  ...
1394456    2018.09.28 23:53:00
1394457    2018.09.28 23:54:00
1394458    2018.09.28 23:55:00
1394459    2018.09.28 23:56:00
1394460    2018.09.28 23:57:00
Name: time, Length: 1394461, dtype: object
canvi de columna
0          AUDCADmicro
1          AUDCADmicro
2          AUDCADmicro
3          AUDCADmicro
4          AUDCADmicro
              ...
1394456    AUDCADmicro
1394457    AUDCADmicro
1394458    AUDCADmicro
1394459    AUDCADmicro
1394460    AUDCADmicro
Name: Symbol(), Length: 1394461, dtype: object
canvi de columna
0          0.94782
1          0.94780
2          0.94792
3          0.94783
4          0.94792
            ...
1394456    0.93212
1394457    0.93179
1394458    0.93158
1394459    0.93166
1394460    0.93105
Name: Price, Length: 1394461, dtype: float64
canvi de columna
0          1
1          1
2          1
3          1
4          1
          ..
1394456   -1
1394457   -1
1394458   -1
1394459   -1
1394460   -1
Name: Direction, Length: 1394461, dtype: int64
canvi de columna
0          0.00007
1         -0.00002
2          0.00012
3         -0.00009
4          0.00009
            ...
1394456    0.00008
1394457   -0.00033
1394458   -0.00021
1394459    0.00008
1394460   -0.00061
Name: DeltaPrice, Length: 1394461, dtype: float64
canvi de columna
0          53.391988
1          52.483368
2          56.428176
3          53.093293
4          55.691732
             ...
1394456    25.636419
1394457    20.457054
1394458    17.998752
1394459    20.504356
1394460    13.189177
Name: rsi_m1_var, Length: 1394461, dtype: float64
canvi de columna
0          52.157859
1          51.816990
2          53.260057
3          52.270412
4          53.211601
             ...
1394456    25.973508
1394457    23.429909
1394458    21.998701
1394459    22.539772
1394460    18.980196
Name: rsi_m5_var, Length: 1394461, dtype: float64
canvi de columna
0          47.679415
1          47.366528
2          48.696027
3          47.782885
4          48.691640
             ...
1394456    30.151151
1394457    28.284498
1394458    27.212406
1394459    27.611099
1394460    24.836495
Name: rsi_m10_var, Length: 1394461, dtype: float64
canvi de columna
0          45.686007
1          45.436176
2          46.502503
3          45.768777
4          46.502503
             ...
1394456    29.137168
1394457    27.652520
1394458    26.784045
1394459    27.108383
1394460    24.816940
Name: rsi_m15_var, Length: 1394461, dtype: float64
canvi de columna
0          40.662099
1          40.347039
2          41.688680
3          40.766381
4          41.688680
             ...
1394456    26.066921
1394457    25.060888
1394458    24.460148
1394459    24.685574
1394460    23.064758
Name: rsi_m30_var, Length: 1394461, dtype: float64
canvi de columna
0          41.691889
1          41.465529
2          42.433939
3          41.766953
4          42.433939
             ...
1394456    23.023531
1394457    22.318165
1394458    21.891368
1394459    22.052018
1394460    20.883458
Name: rsi_h1_var, Length: 1394461, dtype: float64
canvi de columna
0          51.071815
1          50.987560
2          51.350582
3          51.099835
4          51.350582
             ...
1394456    29.534606
1394457    29.036088
1394458    28.727518
1394459    28.844292
1394460    27.977148
Name: rsi_h4_var, Length: 1394461, dtype: float64
canvi de columna
0          58.831343
1          54.415712
2          69.497969
3          53.986812
4          66.321919
             ...
1394456    22.862140
1394457    11.388922
1394458     6.721583
1394459    12.045137
1394460    -9.304947
Name: bbpp_m1_var, Length: 1394461, dtype: float64
canvi de columna
0          69.339446
1          68.635263
2          72.972504
3          69.705988
4          70.680322
             ...
1394456    -8.481379
1394457   -17.224662
1394458    -9.132764
1394459    -7.288595
1394460   -19.678287
Name: bbpp_m5_var, Length: 1394461, dtype: float64
canvi de columna
0          56.018814
1          55.261578
2          59.895909
3          56.407804
4          63.090996
             ...
1394456   -13.895631
1394457   -21.861240
1394458   -26.066131
1394459   -24.536197
1394460   -34.310161
Name: bbpp_m10_var, Length: 1394461, dtype: float64
canvi de columna
0          42.141911
1          41.603353
2          44.924921
3          42.419609
4          44.924921
             ...
1394456    -0.267719
1394457    -5.996509
1394458    -9.344836
1394459    -8.096015
1394460   -16.824940
Name: bbpp_m15_var, Length: 1394461, dtype: float64
canvi de columna
0          26.423467
1          26.021131
2          28.564744
3          26.636357
4          28.564744
             ...
1394456     1.412053
1394457    -2.310734
1394458    -4.563135
1394459    -3.715707
1394460    -9.852620
Name: bbpp_m30_var, Length: 1394461, dtype: float64
canvi de columna
0          15.901405
1          15.600820
2          17.558648
3          16.065979
4          17.558648
             ...
1394456     0.053489
1394457    -2.334962
1394458    -3.805804
1394459    -3.249966
1394460    -7.350244
Name: bbpp_h1_var, Length: 1394461, dtype: float64
canvi de columna
0          51.994140
1          51.799545
2          52.993212
3          52.094074
4          52.993212
             ...
1394456   -11.770561
1394457   -13.356570
1394458   -14.335259
1394459   -13.965197
1394460   -16.702474
Name: bbpp_h4_var, Length: 1394461, dtype: float64
canvi de columna